package org.misikovich.beerisfriend.Foods;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.misikovich.beerisfriend.EffectGiveableFood;
import org.misikovich.beerisfriend.NameWrapper;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Alcohol extends EffectGiveableFood {
    private final List<String> phrases;
    private final List<PotionEffect> potionEffects;
    private final Random random;

    public Alcohol(NameWrapper name, Material material, List<PotionEffect> potionEffects) {
        super(name, material);

        this.potionEffects = potionEffects;
        random = new Random();
        phrases = new ArrayList<>();

        phrases.add("бля шо тут налито яща зблюю");
        phrases.add("ебать меня вставило");
        phrases.add("бля мажет шо піздец");
        phrases.add("да ну нахуооой бляяяяя");
        phrases.add("піздец мне болшье не налівай");
        phrases.add("хорошо пошла");
        phrases.add("Че за херня, я как налитый как три пиздеца!");
        phrases.add("Опять этот пидорас наехал, блять!");
        phrases.add("У меня голова, как после трехдневной пьянки на хуторе!");
        phrases.add("Бля, что за пиздец, я уже третий день валяюсь как убитый!");
        phrases.add("На работе опять все ебанули, пиздец просто!");
        phrases.add("Бля, чувак, где мой косяк? Я тут уже как наркоман без дозы!");
        phrases.add("Охуеть, когда последний раз так напился, я еще школьником был!");
        phrases.add("Пошел нахуй, блять, у меня даже слов нет!");
        phrases.add("Пиздец, как меня всё заебало, я просто ахуеваю!");
        phrases.add("Бля, тут ваще какой-то апокалипсис, все в дрочь!");
        // generated by chatgpt
    }

    @Override
    public void giveEffect(Player player) {
        for (PotionEffect potionEffect : potionEffects) {
            if (potionEffect == null) continue;
            player.addPotionEffect(potionEffect);
        }
        player.sendMessage(phrases.get(random.nextInt(phrases.size() - 1)));
    }

    @Override
    public String toString() {
        return "Alcohol{" +
                "potionEffects=" + potionEffects +
                "} " + super.toString();
    }
}
